[package]
name = "pick-full-wm"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
eframe = { version = "0.36.2", default-features = false, features = ["x11", "default_fonts", "glow"] }
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
shellexpand = "3.1.2"
simplelog = "0.12.2"
toml = "1.1.6"
x11rb = { version = "0.14.0", features = ["randr"] }
